# ===== INPUT =====
# RefSeq / GenBank FTP path

inputdir: input directory with GenBank annotation files

# ===== INPUT AND OUTPUT DIRECTORIES =====
outputdir:
  migale_data: input directory with RefSeq annotation download files of translated CDS
  import_Data_1: input directory with report file for downloaded RefSeq data
  blastp_Groups_2: output directory for BLASTp results

# Output directory for protein clustering
outputdir2: output directory of PPR REL and REC database created for the clustering step 2

# Snakemake working directory
workdir: Snakemake working directory

# ===== BLAST / FILTERING PARAMETERS =====
min_identity: 50
min_coverage: 95
CDS_interval: 10

# ===== Protein parameters for BLASTp result analysis =====
TET: Tet(W)

proteins:
  - Tet(W)
  - protein=relaxase
  - protein=recombinase

MGE:
  - protein=relaxase
  - protein=recombinase

# Groups repository name
# TetMGE = IME_Rho_tet genomes
# MGE    = IME_Rho genomes
# Tet    = RPP genomes
groups_repository:
  - g_TetMGE
  - g_MGE
  - g_Tet

# ===== REFERENCE FILES FOR DATABASE CREATION =====
ref_file:
  r1: PPR reference sequence from the ResFinder database
  r2: canonical reference sequence of relaxase
  r3: canonical reference sequence of recombinase

# ===== REPORTS / METADATA =====
report_1: report file containing the number of annotations in RefSeq translated CDS files for each species
taxonomie_1: NCBI taxonomy file for Bacillota and Actinomycetota data (reworked)
