# ===== INPUT =====
#  RefSeq / GenBank FTP path

inputdir: input directory with genbank annotation files

# ===== INPUT aND OUTPUT DIRECTORIES =====
outputdir:
  migale_data: input directory with refseq annotation download files of translated cds
  import_Data_1: output directory with report fle for downloaded Refseq data
  blastp_Groups_2: output directory for blastp results

# Output directory for protein clustering
outputdir2: output directory of PPR REL and REC create database for clustering step

# Snakemake working directory
workdir: snakemakes working directory

# ===== BLAST / FILTERING PARAMETERS =====
min_identity: 50
min_coverage: 95
CDS_interval: 10

# ===== Proteins parameters for blastp resulst analysis =====
TET: Tet(W)

proteins:
  - Tet(W)
  - protein=relaxase
  - protein=recombinase

MGE:
  - protein=relaxase
  - protein=recombinase

groups repository (TetMGE = IME_Rho_tet genomes, MGE= IME_Rho genomes, Tet = RPP genomes) :
  - g_TetMGE
  - g_MGE
  - g_Tet

# ===== REFERENCE FILES for database creation =====
ref_file:
  r1: PPR reference sequence from resfinder database
  r2: canonical sequence reference of relaxase
  r3: canonical sequence reference of recombinase

# ===== REPORTS / METADATA =====
report_1: /path/to/metadata/dataReport_1.csv
taxonomie_1: NCBI taxonomie file for bacillota and actinomycetota data retravaill√©
