# General configuration for protein clustering
# Paths are generic for public use

# Working directories
workdir: Snakemake working directory
outputdir: data for clustering step 
inputdir: output directory containing files from step 1 (Snakemake)
faa_dir: directory containing RefSeq downloaded files

# Reference file
refseq_t: summary_table_1 path

# Clustering threshold
threshold: 0.9

# Protein names of interest in BLASTp result files
proteins:
  - Tet(W)
  - protein=relaxase
  - protein=recombinase

# Protein name extensions for clusters
prot_name:
  - TET
  - REL
  - REC

# Group names
groups:
  - g_TetMGE
  - g_MGE
  - g_Tet
