# General configuration for the Protein clustering
# Paths are generic for public use

# Working directories
workdir: /path/to/workdir
outputdir: /path/to/outputdir
inputdir: /path/to/inputdir
faa_dir: /path/to/faa_dir

# Reference file
refseq_t: /path/to/RefseqFINALE.csv

# Clustering threshold
threshold: 0.9

# Proteins of interest
proteins:
  - Tet(W)
  - protein=relaxase
  - protein=recombinase

# Simplified protein names
prot_name:
  - TET
  - REL
  - REC

# Groups name
groups:
  - g_TetMGE
  - g_MGE
  - g_Tet
